[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --include=dev"]

[phases.build]
cmds = [
  "npm run build -w packages/shared",
  "npm run build -w apps/backend"
]

[start]
cmd = "node apps/backend/dist/index.js"
